apiVersion: v1
kind: Pod
metadata:
  name: mcp-weather
  labels:
    app: mcp-weather
spec:
  runtimeClassName: edera
  containers:
    - name: mcp-weather
      image: denhamparry/mcp-weather:latest-http
      imagePullPolicy: Always
      env:
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openweather-api-key
              key: OPENWEATHER_API_KEY
              optional: true
